source 'http://rubygems.org'
# Webapp
gem 'sinatra'
  gem 'sinatra-contrib' 
  gem 'shotgun'
  gem 'sprockets'
  gem 'coffee-script'
  gem 'sass'
  gem 'haml'
  gem 'unicorn'
# Websocket
gem 'eventmachine'
gem 'em-websocket'